name: Release Build

on:
  release:
    types: [published]

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # needed to push version bump

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ----------------------------------------------
      # 1. Determine version from release tag
      # ----------------------------------------------
      - name: Determine target version
        id: get_version
        run: |
          version="${{ github.event.release.tag_name }}"
          clean_version=${version#v}  # strip leading v
          echo "clean_version=$clean_version" >> "$GITHUB_OUTPUT"

      # ----------------------------------------------
      # 2. Bump manifest.json version if necessary
      # ----------------------------------------------
      - name: Update manifest.json version field
        run: |
          VERSION="${{ steps.get_version.outputs.clean_version }}"
          sed -i -E "s/\"version\": \"[^\"]+\"/\"version\": \"${VERSION}\"/" manifest.json

      - name: Commit and push version bump (if any)
        env:
          VERSION: ${{ steps.get_version.outputs.clean_version }}
        run: |
          if git diff --quiet manifest.json; then
            echo "No version change detected."
            exit 0
          fi
          git config user.name "Aayush Sinha"
          git config user.email "aayush.aryan@me.com"
          git add manifest.json
          git commit -m "chore: bump manifest version to ${VERSION}"
          git push origin HEAD:main

      # ----------------------------------------------
      # 3. Build Web-Store ZIP
      # ----------------------------------------------
      - name: Install zip & rsync
        run: sudo apt-get update && sudo apt-get install -y zip rsync

      - name: Package extension
        run: |
          set -x
          bash scripts/package-extension.sh tokitab.zip

      - name: Rename ZIP with version
        run: |
          VERSION="${{ steps.get_version.outputs.clean_version }}"
          mv tokitab.zip "tokitab-${VERSION}.zip"

      # ----------------------------------------------
      # 4. Publish artifacts
      # ----------------------------------------------
      - name: Upload artifact to workflow run
        uses: actions/upload-artifact@v4
        with:
          name: tokitab-extension
          path: tokitab-${{ steps.get_version.outputs.clean_version }}.zip
          retention-days: 30

      - name: Debug - List files in workspace
        run: ls -lh

      - name: Attach ZIP to GitHub Release
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION="${{ steps.get_version.outputs.clean_version }}"
          gh release upload "${{ github.event.release.tag_name }}" "$GITHUB_WORKSPACE/tokitab-${VERSION}.zip" --clobber

      - name: Upload to Chrome Web Store
        if: github.event_name == 'release'
        uses: mobilefirstllc/cws-publish@latest
        with:
          action: "publish" # one of: upload, publish, testers
          client_id: ${{ secrets.CLIENT_ID }}
          client_secret: ${{ secrets.CLIENT_SECRET }}
          refresh_token: ${{ secrets.REFRESH_TOKEN }}
          extension_id: ${{ vars.EXTENSION_ID }}
          zip_file: tokitab-${{ steps.get_version.outputs.clean_version }}.zip
